### ISSUE TITLE
XQL not found

### ISSUE THREAD

**Issue by JMorell** [gflze/GFLBans#12]
I am trying to install this project and when I try to install this module, it tells me that it has not been found, it seems that the URL of the gitlab project is inaccessible.

![image](https://github.com/user-attachments/assets/5b965036-e291-408e-bfe4-c6e2e0116972)

**Comment by Vauff** [comment]
It's fixed in https://github.com/gflze/GFLBans/tree/management

**Comment by JMorell** [comment]
oh ok, thanks.
